#!/usr/bin/env ruby

require 'pathname'
require 'yaml'
top_dir = Pathname.new(File.expand_path("../../", __FILE__))

gluent_config = YAML.load_file(top_dir + "config" + "gluent.yml")
ENV['GLUENT_DATA_DIR'] = gluent_config["data_dir"]

require File.expand_path("../../application", __FILE__)

include Gluent

opts = Pry::CLI.parse_options
Pry::CLI.start(opts)
